### ISSUE TITLE
Multiple Continuation Lines

### ISSUE THREAD

**Issue by mmanuel26** [315234/MinimalFortran#1]
Your sublime text plugin is awesome! So far I only need consistent line continuation with highlight. For example, from line 3 - 6 the color is not orange. Can you please fix this? 
![multiple lines fortran](https://f.cloud.github.com/assets/3615417/815546/465fe980-ef2b-11e2-968c-11d82647e7fc.png)

Also I want to know if is possible to add some custom color highlight for special arguments or keywords on mi code such as : TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,MATERL,NDI,NSHR,NTENS,        
NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,                   
 DFGRD0,DFGRD1,NOEL,NPT,KSLAY,KSPT,KSTEP,KINC

**Comment by 315234** [comment]
Due to the way that Sublime Text handles syntax highlighting (it checks each line individually against regular expressions) this would not be trivial to do.

**Comment by mmanuel26** [comment]
I understand, thanks for your reply anyways!

On Tuesday, January 27, 2015, 315234 <notifications@github.com> wrote:

> Due to the way that Sublime Text handles syntax highlighting (it checks
> each line individually against regular expressions) this would not be
> trivial to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/315234/MinimalFortran/issues/1#issuecomment-71639352>.
>


-- 
*Emmanuel Irizarry*
Graduate Student
Mechanical Engineering Department
University of Puerto Rico at Mayagüez

**Comment by 315234** [comment]
If you are running a developer build of Sublime Text, you can try out the new version of the Fortran package which has this feature:

https://github.com/315234/SublimeFortran

**Comment by mmanuel26** [comment]
woW THIS IS GREAT!!!

On Wed, Apr 15, 2015 at 12:01 PM, 315234 <notifications@github.com> wrote:

> If you are running a developer build of Sublime Text, you can try out the
> new version of the Fortran package which has this feature:
>
> https://github.com/315234/SublimeFortran
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/315234/MinimalFortran/issues/1#issuecomment-93460734>.
>



-- 
*Emmanuel Irizarry*
Graduate Student
Mechanical Engineering Department
University of Puerto Rico at Mayagüez
