### ISSUE TITLE
Wrong highlighting for Keyword:DATA

### ISSUE THREAD

**Issue by AqBerendsen** [315234/MinimalFortran#11]
When the keyword DATA is used within a derived type and called, it is wrongly identified as a keyword.

Screenshot:
![identification_of_data](https://cloud.githubusercontent.com/assets/14182911/9757759/c847f494-56e2-11e5-92a3-d8f2212d70f2.png)

Sublime 3 Beta (Build: 3083)
MinimalFortran from Package Control

**Comment by 315234** [comment]
This package is no longer being maintained. Please use this one and report any bugs there: https://github.com/315234/SublimeFortran
