### ISSUE TITLE
Identification of .TRUE. and .FALSE.

### ISSUE THREAD

**Issue by AqBerendsen** [315234/MinimalFortran#12]
As the valuse for logical variables of .TRUE. and .FALSE. are Fortran-standart expressions, it would be helpfull, if they're visually distinct from normal text. 

Suggestion: give them the same expression class as numbers get.

Screenshot of current behaviour:
![proposal_logicalvalues](https://cloud.githubusercontent.com/assets/14182911/9757875/830dfef4-56e3-11e5-9596-25ba80909d09.png)

Sublime 3 Beta (Build: 3083)
MinimalFortran from Package Control

**Comment by 315234** [comment]
I am no longer maintaining this syntax highlighting, but feel free to submit a fix and I will merge it. I have a new syntax package here which already supports this feature: 

https://github.com/315234/SublimeFortran

It requires a developer build to work.

**Comment by AqBerendsen** [comment]
thanks for the heads up!
