### ISSUE TITLE
How to modify fortran's language definition?

### ISSUE THREAD

**Issue by PaleNeutron** [315234/MinimalFortran#2]
I want to add support for `openMP` to `MinimalFortran`.

What I have done is here http://stackoverflow.com/questions/27265512/how-to-modify-sublimes-language-definition

Also I want to add auto-indentation to `MinimalFortran`, but I do not have any experience in writing `tmPerformance` file, any suggestion?

**Comment by 315234** [comment]
Comment/uncomment has been fixed in a recent patch. I'm going to close this issue now because it doesn't seem to have any focus, there are multiple issues being discussed etc. Feel free to open new issues for individual problems that still exist.
