### ISSUE TITLE
Cannot comment/uncomment lines

### ISSUE THREAD

**Issue by dchandan** [315234/MinimalFortran#3]
The comment/uncomment feature does not appear to work with ST3. Do you have any thoughts on how this could be fixed?

Thanks,
Deepak

**Comment by 315234** [comment]
Should be fixed in the latest update.

**Comment by cipri-tom** [comment]
Nice! I wanted this for a long time. Thank you!

Could you maybe, please, instruct me how I could modify it such that the '!' is put as the first character on the line, before the indentation ?
Thanks a lot!
