### ISSUE TITLE
Folding with labels not working

### ISSUE THREAD

**Issue by albertored** [315234/MinimalFortran#5]
When some fragment of codes contains labels for `goto` statements the folding does not work correctly, it is not possible to fold the whole piece of code:

![schermata del 2015-03-18 15 48 19](https://cloud.githubusercontent.com/assets/5650488/6711281/5157cc50-cd86-11e4-95fa-ad67252f874e.png)

After folding:

![schermata del 2015-03-18 15 48 37](https://cloud.githubusercontent.com/assets/5650488/6711282/51581ad4-cd86-11e4-8f14-be4fa9e52b70.png)

**Comment by 315234** [comment]
This is due to the way does folding, which is just based on indentation as far as I know.
