### ISSUE TITLE
Inconsistent colouring for keyword "END"

### ISSUE THREAD

**Issue by AqBerendsen** [315234/MinimalFortran#9]
When defining a derived type, the colouring of

    TYPE X
       ...
    END TYPE X

is inconsistent. The same happens with SUBROUTINE/END SUBROUTINE as well as FUNCTION/END FUNCTION. Sample image is below.

Expected colourscheme:

     brown red
        ...
     brown brown red

Actual colourscheme:

     brown red
        ...
     blue brown red

Screenshot:
![inconsistent_colouring_of_end](https://cloud.githubusercontent.com/assets/14182911/9740199/b75a8924-5653-11e5-8ff7-36ea27bc29c8.png)

**Comment by 315234** [comment]
Unfortunately I don't see a way to fix this. The colour is different because the first "test" is identified as a symbol so that it shows up in ST. If the "end test" was parsed as a symbol then the "end" statement would also show up in the symbol list for the project.
